export type LoginUserInfo = {
  id: number;
  portal_id: number;
  employee_id: number;
  name: string;
  email: string;
  email_verified_at: string;
  remember_token: string;
  role_id: string;
  corporate_id: number;
  department_id: number;
  contact_no: number;
  position: string;
  image_photo: string;
  image_signature: string;
  status: string;
  created_at: string;
  updated_at: string;
  corporate_gst_type: string;
  permissions: PermissionsUserLogin[];
  system_admin: any;
  corporate_admin: any;
  corporate: {
    address_building: string;
    address_district: string;
    address_municipal_city: string;
    address_province: string;
    address_street: string;
    address_unit_floor: string;
    address_zip_code: string;
    alt_contact_no: string;
    alt_email: null;
    assigned_corporate_id: string;
    branch_code: string;
    contact_no: string;
    email: string;
    gst_type: string;
    id: 31;
    logo: string;
    name: string;
    rdo_no: string;
    sec_registration_no: string;
    subscriber_id: string;
    tin: string;
    with_transaction: 0;
  };
};
export type PermissionsUserLogin = {
  access: string[];
  duration: number;
  expiration_date: string;
  menu: string;
};
