export type corporateColumns = {
    assigned_corporate_id: any;
    with_transaction: any;
    id?: number;
    logo: any;
    name: string;
    email: string;
    contact_no: number | null;
    alt_email: string;
    alt_contact_no: number | null;
    address_unit_floor: number | null;
    address_building: string;
    address_street: string;
    address_district: number | null;
    address_municipal_city: string;
    address_province: string;
    address_zip_code: number | null;
    tin?: string;
    branch_code?: number | null;
    gst_type: string;
    rdo_no: number | null;
    sec_registration_no: number | null;
};
export type firstCorporateForm = {
    logo: any;
    name: string;
    tin: string;
    branch_code: number | null;
    gst_type: string;
    rdo_no: number | null;
    sec_registration_no: number | null;
};
export type secondCorporateForm = {
    email: string;
    contact_no: number | null;
    alt_email: string;
    alt_contact_no: number | null;
    address_unit_floor: number | null;
    address_building: string;
    address_street: string;
    address_district: number | null;
    address_municipal_city: string;
    address_province: string;
    address_zip_code: number | null;
};
