import { bool } from "yup";

export type billingPrintType = {
  id: number;
  corporate_id: number;
  user_id: number;
  assigned_customer_id: string;
  class: string;
  type: string;
  name: string;
  individual_co_owner: null;
  individual_citizenship: string;
  individual_birth_date: string;
  company_contact_person: string;
  tin: string;
  branch_code: string;
  registered_address_unit_floor: string;
  registered_address_building: string;
  registered_address_street: string;
  registered_address_district: string;
  registered_address_municipal_city: string;
  registered_address_province: string;
  registered_address_zip_code: string;
  mailing_address_unit_floor: string;
  mailing_address_building: string;
  mailing_address_street: string;
  mailing_address_district: string;
  mailing_address_municipal_city: string;
  mailing_address_province: string;
  mailing_address_zip_code: string;
  image_photo: string;
  image_valid_id: string;
  image_signature: string;
  contact_no: string;
  registered_email: string;
  preferred_email: string;
  status: string;
  billing_invoices: {
    id: number;
    corporate_id: number;
    customer_id: number;
    invoice_no: string;
    billing_date: string;
    due_date: string;
    due_amount: number;
    applied_advances: number;
    queuing_amount: number;
    payment_amount: string;
    status: string;
    post_to_portal: boolean;
    invoice_list: InvoiceListType[];
  }[];
};

export type InvoiceListType = {
  id: number;
  billing_invoice_id: number;
  charge_id: number;
  property_unit_id: number;
  description: "Internet Bill";
  unit_price: number;
  quantity: number;
  vat: number;
  amount: number;
  amount_paid: number;
  adjustment_amount: number;
  billing_batch_list_id: number;
  billing_readings_list_id: number;
  charge: {
    id: number;
    corporate_id: number;
    assigned_charge_id: string;
    code: string;
    type: string;
    name: string;
    description: string;
    base_rate: number;
    charge_uom_id: number;
    vat_percent: number;
    receivable_coa_id: number;
    discounts_coa_id: number;
    revenue_coa_id: number;
    advances_coa_id: number;
    minimum: number;
    interest: string;
    payment_heirarchy: number;
    soa_sort_order: number;
    with_transaction: number;
  };
};
