import { bool } from "yup";

export type billingPrintType = {
  id: number;
  corporate_id: number;
  user_id: number;
  assigned_customer_id: string;
  class: string;
  type: string;
  name: string;
  individual_co_owner: null;
  individual_citizenship: string;
  individual_birth_date: string;
  company_contact_person: string;
  tin: string;
  branch_code: string;
  registered_address_unit_floor: string;
  registered_address_building: string;
  registered_address_street: string;
  registered_address_district: string;
  registered_address_municipal_city: string;
  registered_address_province: string;
  registered_address_zip_code: string;
  mailing_address_unit_floor: string;
  mailing_address_building: string;
  mailing_address_street: string;
  mailing_address_district: string;
  mailing_address_municipal_city: string;
  mailing_address_province: string;
  mailing_address_zip_code: string;
  image_photo: string;
  image_valid_id: string;
  image_signature: string;
  contact_no: string;
  registered_email: string;
  preferred_email: string;
  status: string;
  billing_invoices: {
    id: number;
    corporate_id: number;
    customer_id: number;
    invoice_no: string;
    billing_date: string;
    due_date: string;
    due_amount: number;
    applied_advances: number;
    queuing_amount: number;
    payment_amount: string;
    status: string;
    post_to_portal: boolean;
  }[];
};
